# vim: set sw=2 ts=2 softtabstop=2 expandtab:
language: csharp
dist: xenial
sudo: required
solution: "src/Symbooglix.sln"

addons:
  apt:
    packages:
      - z3

# Each item in the "env" list is a build configuration that will be enumerated
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

install:
  # Install needed python tools
  - sudo pip install lit OutputCheck pyyaml

script:
  - SBX_SRC=`pwd` utils/travis-prepare.sh
  - SBX_SRC=`pwd` utils/travis-build.sh
  - SBX_SRC=`pwd` utils/travis-test.sh
